### ISSUE TITLE
Title seems broken

### ISSUE THREAD

**Issue by cfjedimaster** [pmuellr/md-viewer#12]
I opened the app, and the title says:

/~psn_0_morenumbershere

**Comment by cfjedimaster** [comment]
When I open a file, it correctly shows the file name in the title. So maybe the code should recognize when it is opened w/o a file and prompt the user to select one.

**Comment by pmuellr** [comment]
wops!  I have some "titling" working to do - the "about" page that comes up
should just say "About" and not display the location of the About.md file.
Should get fixed then.

Thanks!

On Thu, Jun 4, 2015 at 2:48 PM, Raymond Camden notifications@github.com
wrote:

> When I open a file, it correctly shows the file name in the title. So
> maybe the code should recognize when it is opened w/o a file and prompt the
> user to select one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/md-viewer/md-viewer/issues/12#issuecomment-109004897.

## 

Patrick Mueller
http://muellerware.org
